Capture generated bindings using command
josephsnyder/drake pull request #3
Opened 2021-01-28 15:24 UTC by EricCousineau-TRI

```
bazel run //bindings/pydrake:autopybind11_example -- --output_dir=${PWD}/tmp/autopybind11
```

Will comment using Reviewable

2021-01-28 15:26 UTC, EricCousineau-TRI commented
@josephsnyder for review please

2021-01-28 15:29 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 6 files reviewed, 2 unresolved discussions

___
*[tmp/autopybind11/drake_py.cpp, line 13 at r1](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8aPp46yvz36CUOGnB:-MS8aPp505fiutKAsT2x:b-n7lvlc) ([raw file](https://github.com/josephsnyder/drake/blob/3784a13c3945bb39d70f5e38c444b857ce0dc527/tmp/autopybind11/drake_py.cpp#L13)):*
> ```cpp
>       .value("absolute", ::drake::ToleranceType::kAbsolute, "")
>       .value("relative", ::drake::ToleranceType::kRelative, "")
>       .export_values();
> ```

I would like this to not export values.

Is this possible?
___
*[tmp/autopybind11/RandomGenerator_py.cpp, line 7 at r1](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8ajBr0rEF__qRgfm0:-MS8ajBr0rEF__qRgfm1:b-1tgnhk) ([raw file](https://github.com/josephsnyder/drake/blob/3784a13c3945bb39d70f5e38c444b857ce0dc527/tmp/autopybind11/RandomGenerator_py.cpp#L7)):*
> ```cpp
> namespace py = pybind11;
> void apb11_pydrake_RandomGenerator_py_register(py::module &m) {
>   static bool called = false;
> ```

I'm not sure if I understand why these guards are here. The concern is that if this is not called the second time, it may return an empty module in Python 3.

Can you point me to the `autopybind11` unittest that exercises this guard?

FWIW This is the macro we use in Drake for similar purposes, but generally this is only for semi-unavoidable cyclic dependencies:
https://github.com/RobotLocomotion/drake/blob/v0.26.0/bindings/pydrake/pydrake_pybind.h#L139-L155


<!-- Sent from Reviewable.io -->

2021-01-28 15:29 UTC, josephsnyder commented
Capturing looks correct to me.  Merging now

2021-01-28 15:29 UTC, EricCousineau-TRI commented
Ah, no! Please don't merge!

2021-01-28 15:29 UTC, EricCousineau-TRI commented
Sorry - this is just to review against something concrete; not meant to be merged in.

2021-01-28 15:30 UTC, josephsnyder commented
Haha, I saw the other comments before I hit the button.  No merging

2021-01-28 15:36 UTC, josephsnyder reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[tmp/autopybind11/drake_py.cpp, line 13 at r1](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8aPp46yvz36CUOGnB:-MS8bcFF4h8vI9c_uNAW:b-s9bwg3) ([raw file](https://github.com/josephsnyder/drake/blob/3784a13c3945bb39d70f5e38c444b857ce0dc527/tmp/autopybind11/drake_py.cpp#L13)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I would like this to not export values.

Is this possible?
</blockquote></details>

We don't have a way to turn this off right now.  It wouldn't be hard to add a customization to do so.
My play will be to default it to not exporing  and supplying  some ``export_enum_values`` flag will append the function call
___
*[tmp/autopybind11/RandomGenerator_py.cpp, line 7 at r1](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8ajBr0rEF__qRgfm0:-MS8cbUEBf2P9fDYnzGn:bnzif2c) ([raw file](https://github.com/josephsnyder/drake/blob/3784a13c3945bb39d70f5e38c444b857ce0dc527/tmp/autopybind11/RandomGenerator_py.cpp#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm not sure if I understand why these guards are here. The concern is that if this is not called the second time, it may return an empty module in Python 3.

Can you point me to the `autopybind11` unittest that exercises this guard?

FWIW This is the macro we use in Drake for similar purposes, but generally this is only for semi-unavoidable cyclic dependencies:
https://github.com/RobotLocomotion/drake/blob/v0.26.0/bindings/pydrake/pydrake_pybind.h#L139-L155
</blockquote></details>

I don't know if we have a test for this at the moment.  It shouldn't be hard to test though, as I think we'll just have to import a module twice to see if it crashes when trying to load the module again.


<!-- Sent from Reviewable.io -->

2021-01-28 15:38 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8cgkd4rK04d8B3wTI:-MS8cgkd4rK04d8B3wTJ:bwbs3fr) (no related file):*
I'm porting some of your stuff from this branch:
https://github.com/josephsnyder/drake-external-examples/tree/add_binding_example_2/drake_cmake_bindings/pydrake

However, I don't understand how the geometry binding generation works:
https://github.com/RobotLocomotion/drake-external-examples/compare/master...josephsnyder:add_binding_example_2#diff-88377387f1f75c3c059a8a3001ed1880d9597e5cbf4401d1498f0265ab27ee6a

Will briefly review autopybind11 docs to see if that is explained...

---
___
*[tmp/autopybind11/drake_py.cpp, line 13 at r1](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8aPp46yvz36CUOGnB:-MS8cz7x9VSivqFrmzOD:b6011jn) ([raw file](https://github.com/josephsnyder/drake/blob/3784a13c3945bb39d70f5e38c444b857ce0dc527/tmp/autopybind11/drake_py.cpp#L13)):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

We don't have a way to turn this off right now.  It wouldn't be hard to add a customization to do so.
My play will be to default it to not exporing  and supplying  some ``export_enum_values`` flag will append the function call

</blockquote></details>

You should also be able to distinguish between a C-syle `enum` (uscoped enumerations) and a C++11 `enum class` (scoped enumerations) via `pygccxml`, right?
https://en.cppreference.com/w/cpp/language/enum#Scoped_enumerations


<!-- Sent from Reviewable.io -->

2021-01-28 15:39 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @josephsnyder)

___
*[tmp/autopybind11/RandomGenerator_py.cpp, line 7 at r1](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8ajBr0rEF__qRgfm0:-MS8dRbB8JEVc1EeuNPy:brixam8) ([raw file](https://github.com/josephsnyder/drake/blob/3784a13c3945bb39d70f5e38c444b857ce0dc527/tmp/autopybind11/RandomGenerator_py.cpp#L7)):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

I don't know if we have a test for this at the moment.  It shouldn't be hard to test though, as I think we'll just have to import a module twice to see if it crashes when trying to load the module again.
</blockquote></details>

Sounds good. You should also make sure that the re-imported module still has some integrity (e.g. the definitions up to that point, or whatever).

I can point to places in our code which fail if we don't have our `PYDRAKE_PREVENT_PYTHON3_MODULE_REIMPORT` workaround.


<!-- Sent from Reviewable.io -->

2021-01-28 15:40 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @josephsnyder)

___
*[tmp/autopybind11/RandomGenerator_py.cpp, line 7 at r1](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8ajBr0rEF__qRgfm0:-MS8dm3pDY8Pi290cZL8:brgjdi4) ([raw file](https://github.com/josephsnyder/drake/blob/3784a13c3945bb39d70f5e38c444b857ce0dc527/tmp/autopybind11/RandomGenerator_py.cpp#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Sounds good. You should also make sure that the re-imported module still has some integrity (e.g. the definitions up to that point, or whatever).

I can point to places in our code which fail if we don't have our `PYDRAKE_PREVENT_PYTHON3_MODULE_REIMPORT` workaround.
</blockquote></details>

See also:
https://github.com/pybind/pybind11/issues/1559


<!-- Sent from Reviewable.io -->

2021-01-28 15:44 UTC, josephsnyder reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8cgkd4rK04d8B3wTI:-MS8eVIUDmF829W4s8OC:b-uwehsw) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I'm porting some of your stuff from this branch:
https://github.com/josephsnyder/drake-external-examples/tree/add_binding_example_2/drake_cmake_bindings/pydrake

However, I don't understand how the geometry binding generation works:
https://github.com/RobotLocomotion/drake-external-examples/compare/master...josephsnyder:add_binding_example_2#diff-88377387f1f75c3c059a8a3001ed1880d9597e5cbf4401d1498f0265ab27ee6a

Will briefly review autopybind11 docs to see if that is explained...
</blockquote></details>

Geometry is well behind all the others.  I cannot remember why I stopped the attempted binding of it, though.  I'll have to revisit it.

---
___
*[tmp/autopybind11/drake_py.cpp, line 13 at r1](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8aPp46yvz36CUOGnB:-MS8cuo9BsCxpVgvIjEC:b-ucw65r) ([raw file](https://github.com/josephsnyder/drake/blob/3784a13c3945bb39d70f5e38c444b857ce0dc527/tmp/autopybind11/drake_py.cpp#L13)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

You should also be able to distinguish between a C-syle `enum` (uscoped enumerations) and a C++11 `enum class` (scoped enumerations) via `pygccxml`, right?
https://en.cppreference.com/w/cpp/language/enum#Scoped_enumerations
</blockquote></details>

That's an upcoming feature. CastXML passes the type of the enumeration in the latest version but pygccxml doesn't handle it yet.  I have a branch to make it do so which is still a WIP. 


<!-- Sent from Reviewable.io -->

2021-01-28 15:46 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8cgkd4rK04d8B3wTI:-MS8f0M59nqDrljDBfpE:bpxkx9k) (no related file):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

Geometry is well behind all the others.  I cannot remember why I stopped the attempted binding of it, though.  I'll have to revisit it.
</blockquote></details>

Ah, so I should ignore that config file for now?

That's fine, just wasn't sure if there were features I was unaware of (like "autodisocover where exactly this belongs).

---


<!-- Sent from Reviewable.io -->

2021-01-28 15:49 UTC, josephsnyder reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8cgkd4rK04d8B3wTI:-MS8flHkB9dUm_o8l6zz:b-n3k6wz) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Ah, so I should ignore that config file for now?

That's fine, just wasn't sure if there were features I was unaware of (like "autodisocover where exactly this belongs).
</blockquote></details>

Yes, please ignore it.  I'll revisit it and see why I left it in such a poor state.  

---


<!-- Sent from Reviewable.io -->

2021-01-28 15:51 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8gIaB7Bep__58g334:-MS8gIaB7Bep__58g335:b-caejqf) (no related file):*
Hit the error I think you alluded to last week:
```
bazel-out/k8-opt/bin/tools/install/libdrake/_virtual_includes/drake_headers/drake/lcm/drake_lcm.h:7:10: fatal error: 'lcm/lcm-cpp.hpp' file
not found
#include "lcm/lcm-cpp.hpp"
```

---


<!-- Sent from Reviewable.io -->

2021-01-28 15:54 UTC, josephsnyder reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8gIaB7Bep__58g334:-MS8gqda7PWpzJOhHRcK:b-7eqwcd) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hit the error I think you alluded to last week:
```
bazel-out/k8-opt/bin/tools/install/libdrake/_virtual_includes/drake_headers/drake/lcm/drake_lcm.h:7:10: fatal error: 'lcm/lcm-cpp.hpp' file
not found
#include "lcm/lcm-cpp.hpp"
```
</blockquote></details>

I guess I didn't add the LCM as a data dependency to the rule.  Whoops!

---


<!-- Sent from Reviewable.io -->

2021-01-28 16:03 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8cgkd4rK04d8B3wTI:-MS8hC328XhgBUrNTzEz:b56uezr) (no related file):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

Yes, please ignore it.  I'll revisit it and see why I left it in such a poor state.  
</blockquote></details>

OK Sounds good!

---
*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8iX640KjwAlbE1kpU:-MS8iX640KjwAlbE1kpV:b-8efgmr) (no related file):*
For the current revision, I'm doing a naive stress-test. It does seem to be very slow (it's been 5 minutes on `r3`, and still haven't seen any output).

I'm also only seeing one core doing work on my 48 core machine.
FWIW, `mkdoc.py` is able to trawl through all of Drake's symbols and generate the docstring tree in about 50-60s, and I believe that is on a single processor.

I will split things up to manually do "parallelization".

Relates https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/158

---
___
*[tmp/autopybind11/drake_py.cpp, line 13 at r1](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8aPp46yvz36CUOGnB:-MS8iOL--S93vcMNFyKr:b753x4x) ([raw file](https://github.com/josephsnyder/drake/blob/3784a13c3945bb39d70f5e38c444b857ce0dc527/tmp/autopybind11/drake_py.cpp#L13)):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

That's an upcoming feature. CastXML passes the type of the enumeration in the latest version but pygccxml doesn't handle it yet.  I have a branch to make it do so which is still a WIP. 
</blockquote></details>

Gotcha. Yeah, I would recommend not exporting values when you can detect a scoped enum.

Is there a GitLab issue for that already?


<!-- Sent from Reviewable.io -->

2021-01-28 16:08 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

___
*[tmp/autopybind11/drake_py.cpp, line 13 at r1](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8aPp46yvz36CUOGnB:-MS8k3nZB3tLPwJYZ5EX:bqifqu3) ([raw file](https://github.com/josephsnyder/drake/blob/3784a13c3945bb39d70f5e38c444b857ce0dc527/tmp/autopybind11/drake_py.cpp#L13)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha. Yeah, I would recommend not exporting values when you can detect a scoped enum.

Is there a GitLab issue for that already?
</blockquote></details>

Per VC: https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/60


<!-- Sent from Reviewable.io -->

2021-01-28 16:14 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8iX640KjwAlbE1kpU:-MS8lACFCpFAoPExZlL7:b-z45csr) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For the current revision, I'm doing a naive stress-test. It does seem to be very slow (it's been 5 minutes on `r3`, and still haven't seen any output).

I'm also only seeing one core doing work on my 48 core machine.
FWIW, `mkdoc.py` is able to trawl through all of Drake's symbols and generate the docstring tree in about 50-60s, and I believe that is on a single processor.

I will split things up to manually do "parallelization".

Relates https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/158
</blockquote></details>

Can point `autopybind11 repository to use this commit:
https://gitlab.kitware.com/autopybind11/autopybind11/-/merge_requests/121
Per VC, can speed up MBP gen from 50min-ish  down to 8min.

Also, got an error when trying to generate bindings with the current config file at r3:
```
$ bazel run --run_under=time //bindings/pydrake:autopybind11_example -- --output_dir=${PWD}/tmp/autopybind11
...
pygccxml.declarations.runtime_errors.multiple_declarations_found_t: Multiple declarations have been found. Matcher: [(decl type==constructor_t)]
...

real    13m18.134s
user    13m2.113s
sys     0m15.936s
```

---


<!-- Sent from Reviewable.io -->

2021-01-28 17:43 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8iX640KjwAlbE1kpU:-MS94ciu9jWPHxqPLf8C:b-w4ww51) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Can point `autopybind11 repository to use this commit:
https://gitlab.kitware.com/autopybind11/autopybind11/-/merge_requests/121
Per VC, can speed up MBP gen from 50min-ish  down to 8min.

Also, got an error when trying to generate bindings with the current config file at r3:
```
$ bazel run --run_under=time //bindings/pydrake:autopybind11_example -- --output_dir=${PWD}/tmp/autopybind11
...
pygccxml.declarations.runtime_errors.multiple_declarations_found_t: Multiple declarations have been found. Matcher: [(decl type==constructor_t)]
...

real    13m18.134s
user    13m2.113s
sys     0m15.936s
```
</blockquote></details>

Same error, but faster! (with https://gitlab.kitware.com/autopybind11/autopybind11/-/tree/bf45caec52c65d2bf6d8d493393e2fbd408c1544)

```
pygccxml.declarations.runtime_errors.multiple_declarations_found_t: Multiple declarations have been found. Matcher: [(decl type==constructor_t)]
...
real    2m50.211s
user    2m43.947s
sys     0m6.192s
```

---


<!-- Sent from Reviewable.io -->

2021-01-28 19:16 UTC, josephsnyder commented
*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8iX640KjwAlbE1kpU:-MS9PGfq0fRWqvARAvhk:bydj56x) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Same error, but faster! (with https://gitlab.kitware.com/autopybind11/autopybind11/-/tree/bf45caec52c65d2bf6d8d493393e2fbd408c1544)

```
pygccxml.declarations.runtime_errors.multiple_declarations_found_t: Multiple declarations have been found. Matcher: [(decl type==constructor_t)]
...
real    2m50.211s
user    2m43.947s
sys     0m6.192s
```
</blockquote></details>

I was able to track the error to line 564-566 in __main__.py of AutoPyBind11. Changing those lines to look like this:

```
                extra_includes.add(
                    dep_class_t.constructors()[0].location.file_name
                )
```

will get you past the error. I'm trying to figure out which dep_class_t object that we reached which has multiple constructors and how to see if we need to stick with the 0th of all of the constructors.

---


<!-- Sent from Reviewable.io -->

2021-01-28 19:36 UTC, josephsnyder reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8iX640KjwAlbE1kpU:-MS9URlx9tQdq2RHZmNK:btgez5o) (no related file):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

I was able to track the error to line 564-566 in __main__.py of AutoPyBind11. Changing those lines to look like this:

```
                extra_includes.add(
                    dep_class_t.constructors()[0].location.file_name
                )
```

will get you past the error. I'm trying to figure out which dep_class_t object that we reached which has multiple constructors and how to see if we need to stick with the 0th of all of the constructors.
</blockquote></details>

Seems to be related to ```Eigen::Matrix<double, -1, 1, 0, -1, 1>```.  Not surprising that that has a >1 constructors. 
 The zero-eth constructor route seems to be the best way forward.  

---


<!-- Sent from Reviewable.io -->

2021-02-04 15:52 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

___
*[tmp/autopybind11/RenderCameraCore_py.cpp, line 7 at r5](https://reviewable.io/reviews/josephsnyder/drake/3#-MShjUAp1oZmyxNo6jsl:-MShjUAp1oZmyxNo6jsm:b-94hqjd) ([raw file](https://github.com/josephsnyder/drake/blob/75828febce9ea9b46fe9890b2ae91d7100101404/tmp/autopybind11/RenderCameraCore_py.cpp#L7)):*
> ```cpp
> 
> namespace py = pybind11;
> void apb11_pydrake_RenderCameraCore_py_register(py::module &m) {
> ```

@josephsnyder This seems to break, silently? On this revision (r5, 75828febce), I do the following to generate this:
```
rm -rf ./tmp/autopybind11/
bazel run //bindings/pydrake:autopybind11_example -- --output_dir=${PWD}/tmp/autopybind11
```

Nothing useful is generated?


<!-- Sent from Reviewable.io -->

2021-02-04 15:54 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8iX640KjwAlbE1kpU:-MShjxLs-SRRb5tlntIl:blyl3uy) (no related file):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

Seems to be related to ```Eigen::Matrix<double, -1, 1, 0, -1, 1>```.  Not surprising that that has a >1 constructors. 
 The zero-eth constructor route seems to be the best way forward.  
</blockquote></details>

Gotcha. I will wait until a fix is ready for `autopybind11` proper; until then, I will see if I can avoid this hot path.

Do you know which class this came up for?

---


<!-- Sent from Reviewable.io -->

2021-02-04 16:00 UTC, josephsnyder reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8iX640KjwAlbE1kpU:-MShlKju1BY6-nPY09YQ:b2ea75k) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Gotcha. I will wait until a fix is ready for `autopybind11` proper; until then, I will see if I can avoid this hot path.

Do you know which class this came up for?
</blockquote></details>

It was AutoDiffXd.  We have a fix but not a test yet.  I'm considering just merging it as is and dealing with the test later.

---


<!-- Sent from Reviewable.io -->

2021-02-04 16:04 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/autopybind11_example.yaml, line 1 at r5](https://reviewable.io/reviews/josephsnyder/drake/3#-MShm6Of5VGPsdpkAyPX:-MShm6Of5VGPsdpkAyPY:b-dcsn2h) ([raw file](https://github.com/josephsnyder/drake/blob/75828febce9ea9b46fe9890b2ae91d7100101404/bindings/pydrake/autopybind11_example.yaml#L1)):*
> ```YAML
> # For additional examples, see the README.rst or
> ```

Working: I will uncomment the classes I would like to inspect/customize per upstream issue.
Given silent failures etc, will then pass to Joe to ensure that it generates the corresponding code.
___
*[tmp/autopybind11/RenderCameraCore_py.cpp, line 7 at r5](https://reviewable.io/reviews/josephsnyder/drake/3#-MShjUAp1oZmyxNo6jsl:-MShmMfxBK825z81HdOf:b-yiunc2) ([raw file](https://github.com/josephsnyder/drake/blob/75828febce9ea9b46fe9890b2ae91d7100101404/tmp/autopybind11/RenderCameraCore_py.cpp#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@josephsnyder This seems to break, silently? On this revision (r5, 75828febce), I do the following to generate this:
```
rm -rf ./tmp/autopybind11/
bazel run //bindings/pydrake:autopybind11_example -- --output_dir=${PWD}/tmp/autopybind11
```

Nothing useful is generated?
</blockquote></details>

(silent: no stdout/stderr, exit status 0)


<!-- Sent from Reviewable.io -->

2021-02-04 17:42 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/autopybind11_example.yaml, line 1 at r5](https://reviewable.io/reviews/josephsnyder/drake/3#-MShm6Of5VGPsdpkAyPX:-MSi7lRj7FTSlUqNz0sX:b3ughnh) ([raw file](https://github.com/josephsnyder/drake/blob/75828febce9ea9b46fe9890b2ae91d7100101404/bindings/pydrake/autopybind11_example.yaml#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: I will uncomment the classes I would like to inspect/customize per upstream issue.
Given silent failures etc, will then pass to Joe to ensure that it generates the corresponding code.
</blockquote></details>

OK I've updated this file with what I would expect to work. (There may still be typos).

@josephsnyder Handing off to you!


<!-- Sent from Reviewable.io -->

2021-02-04 17:43 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[tmp/autopybind11/RenderCameraCore_py.cpp, line 7 at r5](https://reviewable.io/reviews/josephsnyder/drake/3#-MShjUAp1oZmyxNo6jsl:-MSi7t6MBfRhJ2Ba3GXW:b-f67of6) ([raw file](https://github.com/josephsnyder/drake/blob/75828febce9ea9b46fe9890b2ae91d7100101404/tmp/autopybind11/RenderCameraCore_py.cpp#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

(silent: no stdout/stderr, exit status 0)
</blockquote></details>

Is it possible the fact that `inst` isn't defined? e.g. `RenderCameraCore: {}` vs. `RenderCameraCore: {inst: []}`?


<!-- Sent from Reviewable.io -->

2021-02-04 17:47 UTC, josephsnyder commented
___
*[tmp/autopybind11/RenderCameraCore_py.cpp, line 7 at r5](https://reviewable.io/reviews/josephsnyder/drake/3#-MShjUAp1oZmyxNo6jsl:-MSi8vp70k8ul-_-Sw4N:b46g8ne) ([raw file](https://github.com/josephsnyder/drake/blob/75828febce9ea9b46fe9890b2ae91d7100101404/tmp/autopybind11/RenderCameraCore_py.cpp#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Is it possible the fact that `inst` isn't defined? e.g. `RenderCameraCore: {}` vs. `RenderCameraCore: {inst: []}`?
</blockquote></details>

It shouldn't be.  The absence of ``inst`` is treated the same as an empty list


<!-- Sent from Reviewable.io -->

2021-02-18 16:20 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MTpvvYoCyy7wrFR9rbl:-MTpvvYp8u_qHLchHg_j:b-ppag4o) (no related file):*
Working: I should review the current bindings being generated.

---


<!-- Sent from Reviewable.io -->

2021-02-25 15:58 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 22 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[tools/workspace/autopybind11_py/repository.bzl, line 12 at r9](https://reviewable.io/reviews/josephsnyder/drake/3#-MUOu6kTD6K4aEJQ1t5i:-MUOu6kTD6K4aEJQ1t5j:bqie542) ([raw file](https://github.com/josephsnyder/drake/blob/a52ea16e0147373181254caf99911e4a0f04a942/tools/workspace/autopybind11_py/repository.bzl#L12)):*
> ```Starlark
>         # Temporary branch
>         repository = "joe-snyder/autopybind11",
>         commit = "template_alias_fixes",
> ```

I get a 404 here :(

```
$ git log -n 1 --oneline --no-decorate
a52ea16e01 Merge remote-tracking branch 'upstream/master' into test_autopybind_integration-eric-gen-review
$ bazel run //bindings/pydrake:autopybind11_example --     --output_dir=/tmp/autopybind11
...
  .../drake/tools/workspace/autopybind11_py/repository.bzl:8:19: in autopybind11_py_repository
...
WARNING: Download from https://gitlab.kitware.com/joe-snyder/autopybind11/-/archive/template_alias_fixes/autopybind11-template_alias_fixes.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
...
Error in download_and_extract: java.io.IOException: Error downloading [https://gitlab.kitware.com/joe-snyder/autopybind11/-/archive/template_alias_fixes/autopybind11-template_alias_fixes.tar.gz] to /mnt/ssd2/eacousineau/cache/bazel/_bazel_eacousineau/b2e564e32f8ad0fdcd9d9d860a1def41/external/autopybind11_py/temp9614378420423903057/autopybind11-template_alias_fixes.tar.gz: GET returned 404 Not Found
```


<!-- Sent from Reviewable.io -->

2021-02-25 16:20 UTC, EricCousineau-TRI commented
___
*[bindings/pydrake/autopybind11_example.yaml, line 100 at r9](https://reviewable.io/reviews/josephsnyder/drake/3#-MUOzJMp2gibVyew-0mj:-MUOzJMp2gibVyew-0mk:bpx3u7t) ([raw file](https://github.com/josephsnyder/drake/blob/a52ea16e0147373181254caf99911e4a0f04a942/bindings/pydrake/autopybind11_example.yaml#L100)):*
> ```YAML
>                 Environment: {}
>                 Formula: {}
>                 # FormulaCell marked as class_declaration_t not a class_t
> ```

Hoisting warning to a Reviewable comment.


<!-- Sent from Reviewable.io -->

2021-02-25 16:22 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 22 files reviewed, 8 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/autopybind11_example.yaml, line 100 at r9](https://reviewable.io/reviews/josephsnyder/drake/3#-MUOzJMp2gibVyew-0mj:-MUOzmuYBJthu8e7XM-2:bvm4osb) ([raw file](https://github.com/josephsnyder/drake/blob/a52ea16e0147373181254caf99911e4a0f04a942/bindings/pydrake/autopybind11_example.yaml#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hoisting warning to a Reviewable comment.
</blockquote></details>

Working: I should determine if this needs to be bound.


<!-- Sent from Reviewable.io -->

2021-02-25 16:22 UTC, EricCousineau-TRI commented
___
*[bindings/pydrake/autopybind11_example.yaml, line 1 at r9](https://reviewable.io/reviews/josephsnyder/drake/3#-MUOztvvBtKXms_o-1MK:-MUOztvw-S3w0H-9v1dw:bfm51wy) ([raw file](https://github.com/josephsnyder/drake/blob/a52ea16e0147373181254caf99911e4a0f04a942/bindings/pydrake/autopybind11_example.yaml#L1)):*
> ```YAML
> # For additional examples, see the README.rst or
> ```

Working: Should do this item-by-item given new recursive parsing for name hash table resolution.


<!-- Sent from Reviewable.io -->

2021-02-25 16:44 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 22 files reviewed, 8 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[tools/workspace/autopybind11_py/repository.bzl, line 12 at r9](https://reviewable.io/reviews/josephsnyder/drake/3#-MUOu6kTD6K4aEJQ1t5i:-MUP3rjl53u3_diuoMo6:b-o9j9qj) ([raw file](https://github.com/josephsnyder/drake/blob/a52ea16e0147373181254caf99911e4a0f04a942/tools/workspace/autopybind11_py/repository.bzl#L12)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I get a 404 here :(

```
$ git log -n 1 --oneline --no-decorate
a52ea16e01 Merge remote-tracking branch 'upstream/master' into test_autopybind_integration-eric-gen-review
$ bazel run //bindings/pydrake:autopybind11_example --     --output_dir=/tmp/autopybind11
...
  .../drake/tools/workspace/autopybind11_py/repository.bzl:8:19: in autopybind11_py_repository
...
WARNING: Download from https://gitlab.kitware.com/joe-snyder/autopybind11/-/archive/template_alias_fixes/autopybind11-template_alias_fixes.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
...
Error in download_and_extract: java.io.IOException: Error downloading [https://gitlab.kitware.com/joe-snyder/autopybind11/-/archive/template_alias_fixes/autopybind11-template_alias_fixes.tar.gz] to /mnt/ssd2/eacousineau/cache/bazel/_bazel_eacousineau/b2e564e32f8ad0fdcd9d9d860a1def41/external/autopybind11_py/temp9614378420423903057/autopybind11-template_alias_fixes.tar.gz: GET returned 404 Not Found
```
</blockquote></details>

Done via Joe's push.


<!-- Sent from Reviewable.io -->

2021-02-25 16:45 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 22 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8iX640KjwAlbE1kpU:-MUP45SP1oC00j7UGK-l:b-ih5knm) (no related file):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

It was AutoDiffXd.  We have a fix but not a test yet.  I'm considering just merging it as is and dealing with the test later.
</blockquote></details>

OK Marking as resolved via https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/170

---


<!-- Sent from Reviewable.io -->

2021-02-25 16:47 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 22 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/autopybind11_example.yaml, line 100 at r9](https://reviewable.io/reviews/josephsnyder/drake/3#-MUOzJMp2gibVyew-0mj:-MUP4Rs1EgwsLqcY-rjl:bgwngwn) ([raw file](https://github.com/josephsnyder/drake/blob/a52ea16e0147373181254caf99911e4a0f04a942/bindings/pydrake/autopybind11_example.yaml#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: I should determine if this needs to be bound.
</blockquote></details>

My read on this symbol is that it is only a nice-to-have. Will remove in subsequent push.


<!-- Sent from Reviewable.io -->

2021-02-25 16:48 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 22 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8gIaB7Bep__58g334:-MUP4nye9fC4LVT_Q9NF:ba1lhth) (no related file):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

I guess I didn't add the LCM as a data dependency to the rule.  Whoops!
</blockquote></details>

Hm... this part is still broken. Lemme see if it's easy to fix.

---


<!-- Sent from Reviewable.io -->

2021-02-25 16:50 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 22 files reviewed, 6 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8gIaB7Bep__58g334:-MUP5Ig027BSdn7MFMxi:b-wlqkvs) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Hm... this part is still broken. Lemme see if it's easy to fix.
</blockquote></details>

Done. Seemed like just adding it fixed it.

---


<!-- Sent from Reviewable.io -->

2021-02-25 17:14 UTC, EricCousineau-TRI commented
___
*[tmp/autopybind11/RenderCameraCore_py.cpp, line 7 at r5](https://reviewable.io/reviews/josephsnyder/drake/3#-MShjUAp1oZmyxNo6jsl:-MUPAgN82oBfx11b-3Z6:br7fl80) ([raw file](https://github.com/josephsnyder/drake/blob/75828febce9ea9b46fe9890b2ae91d7100101404/tmp/autopybind11/RenderCameraCore_py.cpp#L7)):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

It shouldn't be.  The absence of ``inst`` is treated the same as an empty list
</blockquote></details>

Done. Fixed now!


<!-- Sent from Reviewable.io -->

2021-02-25 17:15 UTC, EricCousineau-TRI commented
___
*[tmp/autopybind11/RenderCameraCore_py.cpp, line 37 at r11](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPAjKe6pHjio8xfKCX:-MUPAjKe6pHjio8xfKCY:bpvqqkk) ([raw file](https://github.com/josephsnyder/drake/blob/59c6554e58255ae28f613d1c97e48b4ab78fd189/tmp/autopybind11/RenderCameraCore_py.cpp#L37)):*
> ```cpp
>     .def("sensor_pose_in_camera_body", static_cast<::drake::math::RigidTransformd const & ( ::drake::geometry::render::RenderCameraCore::* )(  )const>(&::drake::geometry::render::RenderCameraCore::sensor_pose_in_camera_body), "/** The pose of the sensor frame (S) in the camera's body frame (B). This is \
>  the "imager" referred to in systems::sensors::CameraInfo's documentation.  */")
>     .def("CalcProjectionMatrix", static_cast<::Eigen::Matrix4d ( ::drake::geometry::render::RenderCameraCore::* )(  )const>(&::drake::geometry::render::RenderCameraCore::CalcProjectionMatrix), "/** Expresses `this` camera's pinhole camera properties as the projective \
> ```

Pure `autopybind11` issue: Docstrings should be escaped or surrounded with unlikely-to-be-copied tokens.

For Drake, we use the following literals:
https://drake.mit.edu/styleguide/cppguide.html#Raw_String_Literals

Example from mkdoc test:
https://github.com/RobotLocomotion/drake/blob/v0.27.0/tools/workspace/pybind11/test/sample_header_documentation.expected.h#L20-L21


<!-- Sent from Reviewable.io -->

2021-02-25 17:17 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 65 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[tmp/autopybind11/AutoDiffXd_py.cpp, line 22 at r11](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPBWpk8PrjFZ67Jmyh:-MUPBWpk8PrjFZ67Jmyi:buc96g1) ([raw file](https://github.com/josephsnyder/drake/blob/59c6554e58255ae28f613d1c97e48b4ab78fd189/tmp/autopybind11/AutoDiffXd_py.cpp#L22)):*
> ```cpp
>     .def(py::init<Eigen::Ref<::Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1, 0, -1, 1>>::Scalar const &, 0, Eigen::Stride<Eigen::Dynamic, Eigen::Dynamic>> &,int,int>(),py::arg("value"),py::arg("nbDer"),py::arg("derNumber"))
>     .def(py::init<Eigen::Ref<::Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1, 0, -1, 1>>::Real const &, 0, Eigen::Stride<Eigen::Dynamic, Eigen::Dynamic>> &>(),py::arg("value"))
>     .def(py::init<Eigen::Ref<::Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1, 0, -1, 1>>::Scalar const &, 0, Eigen::Stride<Eigen::Dynamic, Eigen::Dynamic>> &,Eigen::Ref<::Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1, 0, -1, 1>>::DerType const &, 0, Eigen::Stride<Eigen::Dynamic, Eigen::Dynamic>> &>(),py::arg("value"),py::arg("der"))
> ```

Current pain point:
These bindings, using fully-expanded type names with `static_cast`, are extremely hard to read, and thus would be extremely hard to review in a PR bootstrapping with this tool.

See more readable example:
https://github.com/RobotLocomotion/drake/blob/v0.27.0/bindings/pydrake/autodiffutils_py.cc#L38
```
      .def(py::init<const double&, const VectorXd&>())
```


<!-- Sent from Reviewable.io -->

2021-02-25 17:35 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 67 files reviewed, 10 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPEu0P9Flyqdg8YKVC:-MUP4m-X85d-1jh7oz5q:bvtwurk) (no related file):*
Working: Timing info.

On my machine (nproc: 24 x 2 hyperhtread, Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz), on commit 666928b2f9, running the debug script:
* mkdoc for `documentation_pybind.h` takes 35s for filtered Drake symbols
* autopybind11 takes 80s for selected symbols

---
___
*[tmp/autopybind11/AutoDiffXd_py.cpp, line 30 at r12](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPFRvO0koXrQCDvdcd:-MUPFRvO0koXrQCDvdce:b37pkfu) ([raw file](https://github.com/josephsnyder/drake/blob/666928b2f99606f38f23480d606ffc83c3d5ad6e/tmp/autopybind11/AutoDiffXd_py.cpp#L30)):*
> ```cpp
>     .def("derivatives", static_cast<::Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1, 0, -1, 1>>::DerType & ( ::Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1, 0, -1, 1>>::* )(  )>(&::Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1, 0, -1, 1>>::derivatives), "", py::return_value_policy::reference_internal)
>     
>     .def("__gt__", +[](::Eigen::ArrayBase<Eigen::ArrayWrapper<const Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<Eigen::AutoDiffScalar<Eigen::VectorXd>, Eigen::AutoDiffScalar<Eigen::VectorXd>>, const Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::VectorXd>, 3, 3, 0, 3, 3>, const Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::VectorXd>, 3, 3, 0, 3, 3>>>>::Scalar const & s,::Eigen::ArrayWrapper<const Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<Eigen::AutoDiffScalar<Eigen::VectorXd>, Eigen::AutoDiffScalar<Eigen::VectorXd>>, const Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::VectorXd>, 3, 3, 0, 3, 3>, const Eigen::Matrix<Eigen::AutoDiffScalar<Eigen::VectorXd>, 3, 3, 0, 3, 3>>> const & d){ return s>d; })
> ```

Working: This appeared to change run-to-run. Non-deterministic output (e.g. diff. output given same input) will be painful to check.

Order of ops aren't necessarily a pain point (don't care if `output.txt` stays the same), but the output files should maintain the same ordering of bound symbols.

Will try one more time.
___
*[tmp/autopybind11/BarycentricMesh_py.cpp, line 14 at r11](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPCIiY3SbCXwiK_QYq:-MUPCIiY3SbCXwiK_QYr:bc04p84) ([raw file](https://github.com/josephsnyder/drake/blob/59c6554e58255ae28f613d1c97e48b4ab78fd189/tmp/autopybind11/BarycentricMesh_py.cpp#L14)):*
> ```cpp
>   }
>   called = true;
>   py::class_<::drake::math::BarycentricMesh<double>> BarycentricMesh_double(
> ```

For template instantiations, we ultimately need them in the following form:

https://github.com/RobotLocomotion/drake/blob/v0.27.0/bindings/pydrake/math_py.cc#L323-L357
```
py::class_<BarycentricMesh<T>>(m, "BarycentricMesh", doc.BarycentricMesh.doc)
   ...
```

Is that easy to do with current setup? (will check)


<!-- Sent from Reviewable.io -->

2021-02-25 17:39 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 67 files reviewed, 10 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[tmp/autopybind11/AutoDiffXd_py.cpp, line 30 at r12](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPFRvO0koXrQCDvdcd:-MUPGUQ77AzTC_3kivTg:bn8y0o1) ([raw file](https://github.com/josephsnyder/drake/blob/666928b2f99606f38f23480d606ffc83c3d5ad6e/tmp/autopybind11/AutoDiffXd_py.cpp#L30)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: This appeared to change run-to-run. Non-deterministic output (e.g. diff. output given same input) will be painful to check.

Order of ops aren't necessarily a pain point (don't care if `output.txt` stays the same), but the output files should maintain the same ordering of bound symbols.

Will try one more time.
</blockquote></details>

Confirmed for r12..r13. This should be updated to be deterministic in ordering for output files.


<!-- Sent from Reviewable.io -->

2021-02-25 17:44 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 67 files reviewed, 11 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[tmp/autopybind11/BarycentricMesh_py.cpp, line 70 at r13](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPGkhf1AJEhHdjNw13:-MUPGkhf1AJEhHdjNw14:bqmgbbv) ([raw file](https://github.com/josephsnyder/drake/blob/9b7bcc24fb3de69b0e8d99a1c74915325c98ee88/tmp/autopybind11/BarycentricMesh_py.cpp#L70)):*
> ```cpp
>                ::drake::math::BarycentricMesh<double>::*)() const>(
>                &::drake::math::BarycentricMesh<double>::get_all_mesh_points),
>            "/// Returns a matrix with all of the mesh points, one per column.")
> ```

I don't get why these docstrings sometimes appear, and sometimes don't.

mkdoc does not struggle (at least for how it generates symbols).
See: https://github.com/josephsnyder/drake/blob/9b7bcc24fb3de69b0e8d99a1c74915325c98ee88/tmp/autopybind11/documentation_pybind.h
Lines 16227-16382

Snippet:
https://gist.github.com/EricCousineau-TRI/9b0ee45c2ae460420aa88883d841ab0d


<!-- Sent from Reviewable.io -->

2021-02-25 17:44 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 67 files reviewed, 10 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/autopybind11_example.yaml, line 1 at r9](https://reviewable.io/reviews/josephsnyder/drake/3#-MUOztvvBtKXms_o-1MK:-MUPHkFq-pANuIa4QK6G:b3dmpak) ([raw file](https://github.com/josephsnyder/drake/blob/a52ea16e0147373181254caf99911e4a0f04a942/bindings/pydrake/autopybind11_example.yaml#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: Should do this item-by-item given new recursive parsing for name hash table resolution.
</blockquote></details>

OK Not necessary. This only takes 80s on my system.


<!-- Sent from Reviewable.io -->

2021-02-25 17:49 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 66 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[bindings/pydrake/autopybind11_example.yaml, line 100 at r9](https://reviewable.io/reviews/josephsnyder/drake/3#-MUOzJMp2gibVyew-0mj:-MUPIdu0D9oI3QoSlEDE:b-itoud0) ([raw file](https://github.com/josephsnyder/drake/blob/a52ea16e0147373181254caf99911e4a0f04a942/bindings/pydrake/autopybind11_example.yaml#L100)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

My read on this symbol is that it is only a nice-to-have. Will remove in subsequent push.
</blockquote></details>

Done. De-scoped for now.


<!-- Sent from Reviewable.io -->

2021-02-25 18:08 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 66 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MTpvvYoCyy7wrFR9rbl:-MUPMU0gA4rNu-Uh13Nb:b-hx7ods) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Working: I should review the current bindings being generated.
</blockquote></details>

@josephsnyder I've added some comments.

In terms of immediate priority, see below comments:

- Being able to use our custom template instantiation
- Deterministic ordering.
- Better readability for symbols - e.g. using the shortest possible symbol in a given scope.

Things to punt for now:

- Docstring generation - let's punt on iterating on this until we have better feature parity on `mkdoc`. For MVP, let's remove docstrings / docstring symbols.

Can you comment on these respective comments, and formulate them into GitLab issues? (all of them?)

---
___
*[tmp/autopybind11/BarycentricMesh_py.cpp, line 70 at r13](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPGkhf1AJEhHdjNw13:-MUPN87D-9nASv8EV1RO:bcot9o2) ([raw file](https://github.com/josephsnyder/drake/blob/9b7bcc24fb3de69b0e8d99a1c74915325c98ee88/tmp/autopybind11/BarycentricMesh_py.cpp#L70)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I don't get why these docstrings sometimes appear, and sometimes don't.

mkdoc does not struggle (at least for how it generates symbols).
See: https://github.com/josephsnyder/drake/blob/9b7bcc24fb3de69b0e8d99a1c74915325c98ee88/tmp/autopybind11/documentation_pybind.h
Lines 16227-16382

Snippet:
https://gist.github.com/EricCousineau-TRI/9b0ee45c2ae460420aa88883d841ab0d
</blockquote></details>

We should punt on this work for now. However, there should be an issue.
___
*[tmp/autopybind11/RenderCameraCore_py.cpp, line 37 at r11](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPAjKe6pHjio8xfKCX:-MUPNE1oAtnEP2-HuXTZ:bcot9o2) ([raw file](https://github.com/josephsnyder/drake/blob/59c6554e58255ae28f613d1c97e48b4ab78fd189/tmp/autopybind11/RenderCameraCore_py.cpp#L37)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Pure `autopybind11` issue: Docstrings should be escaped or surrounded with unlikely-to-be-copied tokens.

For Drake, we use the following literals:
https://drake.mit.edu/styleguide/cppguide.html#Raw_String_Literals

Example from mkdoc test:
https://github.com/RobotLocomotion/drake/blob/v0.27.0/tools/workspace/pybind11/test/sample_header_documentation.expected.h#L20-L21
</blockquote></details>

We should punt on this work for now. However, there should be an issue.


<!-- Sent from Reviewable.io -->

2021-02-25 19:33 UTC, josephsnyder commented
___
*[tmp/autopybind11/RenderCameraCore_py.cpp, line 37 at r11](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPAjKe6pHjio8xfKCX:-MUPfXETC130EHxcwzvz:b-qf7imq) ([raw file](https://github.com/josephsnyder/drake/blob/59c6554e58255ae28f613d1c97e48b4ab78fd189/tmp/autopybind11/RenderCameraCore_py.cpp#L37)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

We should punt on this work for now. However, there should be an issue.
</blockquote></details>

Issue has been created here: https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/173.  Should be a fairly easy fix.


<!-- Sent from Reviewable.io -->

2021-02-25 19:52 UTC, josephsnyder requested changes
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 66 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

___
*[tmp/autopybind11/AutoDiffXd_py.cpp, line 30 at r12](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPFRvO0koXrQCDvdcd:-MUPgQyH9H657h3drV10:b-r29rry) ([raw file](https://github.com/josephsnyder/drake/blob/666928b2f99606f38f23480d606ffc83c3d5ad6e/tmp/autopybind11/AutoDiffXd_py.cpp#L30)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Confirmed for r12..r13. This should be updated to be deterministic in ordering for output files.
</blockquote></details>

Working: Issue created and selected for current work: https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/174
___
*[tmp/autopybind11/BarycentricMesh_py.cpp, line 14 at r11](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPCIiY3SbCXwiK_QYq:-MUPjzjR1cJjYA2lRCrf:b-hhkpgf) ([raw file](https://github.com/josephsnyder/drake/blob/59c6554e58255ae28f613d1c97e48b4ab78fd189/tmp/autopybind11/BarycentricMesh_py.cpp#L14)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

For template instantiations, we ultimately need them in the following form:

https://github.com/RobotLocomotion/drake/blob/v0.27.0/bindings/pydrake/math_py.cc#L323-L357
```
py::class_<BarycentricMesh<T>>(m, "BarycentricMesh", doc.BarycentricMesh.doc)
   ...
```

Is that easy to do with current setup? (will check)
</blockquote></details>

Both this and the above information about minimizing template output have been captured here: 

https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/175


<!-- Sent from Reviewable.io -->

2021-03-04 13:39 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 66 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

___
*[tmp/autopybind11/BarycentricMesh_py.cpp, line 14 at r11](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPCIiY3SbCXwiK_QYq:-MUxS1jG-wT4ZslYci0w:b80gtbz) ([raw file](https://github.com/josephsnyder/drake/blob/59c6554e58255ae28f613d1c97e48b4ab78fd189/tmp/autopybind11/BarycentricMesh_py.cpp#L14)):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

Both this and the above information about minimizing template output have been captured here: 

https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/175
</blockquote></details>

I derp'ed on my comment here :facepalm: 

I mean to point to this class for a template instantiation:
https://github.com/RobotLocomotion/drake/blob/v0.27.0/bindings/pydrake/math_py.cc#L41-L51

The fully inlined version of it is:
```
DefineTemplateClassWithDefault<RigidTransfor<T>>(
    m, "RigidTransform", GetPyParam<T>(), doc.RigidTransform.doc)
...
```


<!-- Sent from Reviewable.io -->

2021-03-04 13:47 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 66 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

___
*[tmp/autopybind11/AutoDiffXd_py.cpp, line 30 at r12](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPFRvO0koXrQCDvdcd:-MUxUPxA1blsRCjmioEc:b-14l2am) ([raw file](https://github.com/josephsnyder/drake/blob/666928b2f99606f38f23480d606ffc83c3d5ad6e/tmp/autopybind11/AutoDiffXd_py.cpp#L30)):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

Working: Issue created and selected for current work: https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/174
</blockquote></details>

Names are now sorted; however, the ordering of overloads is still not sorted:
32bc265780

Can you ensure that the full signature is sorted, since there seems to be difference in how it's iterated upon in pygccxml / castxml / whatever?


<!-- Sent from Reviewable.io -->

2021-03-04 14:24 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 66 files reviewed, 9 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

___
*[tmp/autopybind11/AutoDiffXd_py.cpp, line 22 at r11](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPBWpk8PrjFZ67Jmyh:-MUxbbSVBuXjtxTelbSU:bhtkkka) ([raw file](https://github.com/josephsnyder/drake/blob/59c6554e58255ae28f613d1c97e48b4ab78fd189/tmp/autopybind11/AutoDiffXd_py.cpp#L22)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Current pain point:
These bindings, using fully-expanded type names with `static_cast`, are extremely hard to read, and thus would be extremely hard to review in a PR bootstrapping with this tool.

See more readable example:
https://github.com/RobotLocomotion/drake/blob/v0.27.0/bindings/pydrake/autodiffutils_py.cc#L38
```
      .def(py::init<const double&, const VectorXd&>())
```
</blockquote></details>

Seperated this issue out in GitLab:
https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/179
___
*[tmp/autopybind11/BarycentricMesh_py.cpp, line 14 at r11](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPCIiY3SbCXwiK_QYq:-MUxbnZcDbGOFVj0SkSZ:b7495cp) ([raw file](https://github.com/josephsnyder/drake/blob/59c6554e58255ae28f613d1c97e48b4ab78fd189/tmp/autopybind11/BarycentricMesh_py.cpp#L14)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

I derp'ed on my comment here :facepalm: 

I mean to point to this class for a template instantiation:
https://github.com/RobotLocomotion/drake/blob/v0.27.0/bindings/pydrake/math_py.cc#L41-L51

The fully inlined version of it is:
```
DefineTemplateClassWithDefault<RigidTransfor<T>>(
    m, "RigidTransform", GetPyParam<T>(), doc.RigidTransform.doc)
...
```
</blockquote></details>

Scoped GitLab autopybind11 issue 175 to just be for templates; I miscommunicated with wrong snippet, sorry!


<!-- Sent from Reviewable.io -->

2021-03-04 16:15 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 66 files reviewed, 8 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

___
*[tmp/autopybind11/RenderCameraCore_py.cpp, line 37 at r11](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPAjKe6pHjio8xfKCX:-MUy0TcUA6IuNDR6v_am:b-3i58es) ([raw file](https://github.com/josephsnyder/drake/blob/59c6554e58255ae28f613d1c97e48b4ab78fd189/tmp/autopybind11/RenderCameraCore_py.cpp#L37)):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

Issue has been created here: https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/173.  Should be a fairly easy fix.
</blockquote></details>

Done via latest push from Joe.


<!-- Sent from Reviewable.io -->

2021-03-04 16:25 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 66 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

___
*[tmp/autopybind11/drake_py.cpp, line 13 at r1](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8aPp46yvz36CUOGnB:-MUy0x0o3Tvabh3LQlXD:b-3h4anw) ([raw file](https://github.com/josephsnyder/drake/blob/3784a13c3945bb39d70f5e38c444b857ce0dc527/tmp/autopybind11/drake_py.cpp#L13)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Per VC: https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/60
</blockquote></details>

Done. No longer exports by default.
___
*[tmp/autopybind11/RandomGenerator_py.cpp, line 7 at r1](https://reviewable.io/reviews/josephsnyder/drake/3#-MS8ajBr0rEF__qRgfm0:-MUy253h6eLteB4k-2lE:b-teu8lq) ([raw file](https://github.com/josephsnyder/drake/blob/3784a13c3945bb39d70f5e38c444b857ce0dc527/tmp/autopybind11/RandomGenerator_py.cpp#L7)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

See also:
https://github.com/pybind/pybind11/issues/1559
</blockquote></details>

Re-scoped to binding sub-routines. Punting to GitLab issue: https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/168

Not blocking for MVP.
___
*[tmp/autopybind11/RollPitchYaw_py.cpp, line 95 at r16](https://reviewable.io/reviews/josephsnyder/drake/3#-MUy2IAeBPkm7Zp8EuBH:-MUy2IAeBPkm7Zp8EuBI:b-473um8) ([raw file](https://github.com/josephsnyder/drake/blob/32bc2657806ef6e16b41eb45322c475d187cc433/tmp/autopybind11/RollPitchYaw_py.cpp#L95)):*
> ```cpp
>              return self.CalcRpyDtFromAngularVelocityInParent(w_AD_A);
>            })
>       .def_static("DRAKE_COPYABLE_DEMAND_COPY_CAN_COMPILE",
> ```

This symbol should be rejected at a global level. (e.g. reject list or skip list)


<!-- Sent from Reviewable.io -->

2021-03-04 16:26 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 66 files reviewed, 7 unresolved discussions (waiting on @EricCousineau-TRI and @josephsnyder)

___
*[tmp/autopybind11/RollPitchYaw_py.cpp, line 95 at r16](https://reviewable.io/reviews/josephsnyder/drake/3#-MUy2IAeBPkm7Zp8EuBH:-MUy2mSE0lrfPJfB6kZU:b7nlr6p) ([raw file](https://github.com/josephsnyder/drake/blob/32bc2657806ef6e16b41eb45322c475d187cc433/tmp/autopybind11/RollPitchYaw_py.cpp#L95)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

This symbol should be rejected at a global level. (e.g. reject list or skip list)
</blockquote></details>

Encoded in https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/182


<!-- Sent from Reviewable.io -->

2021-03-16 15:23 UTC, josephsnyder approved these changes
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 66 files reviewed, 8 unresolved discussions (waiting on @EricCousineau-TRI)

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MTpvvYoCyy7wrFR9rbl:-MVvbUcb9LFjsaR_SXud:bjl3jkr) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@josephsnyder I've added some comments.

In terms of immediate priority, see below comments:

- Being able to use our custom template instantiation
- Deterministic ordering.
- Better readability for symbols - e.g. using the shortest possible symbol in a given scope.

Things to punt for now:

- Docstring generation - let's punt on iterating on this until we have better feature parity on `mkdoc`. For MVP, let's remove docstrings / docstring symbols.

Can you comment on these respective comments, and formulate them into GitLab issues? (all of them?)
</blockquote></details>

Ok.  Issues have been created 

https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/179
https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/174
https://gitlab.kitware.com/autopybind11/autopybind11/-/issues/173

---
*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MVvcGv3BypJ2frrlGi3:-MVvcGv43az5t0cJLnmv:b-ffciwg) (no related file):*
Per F2F with Jamie, we want to move forward with this to try and get the main pull request (https://github.com/RobotLocomotion/drake/pull/14265) merged before end of contract.

---
___
*[tmp/autopybind11/AutoDiffXd_py.cpp, line 30 at r12](https://reviewable.io/reviews/josephsnyder/drake/3#-MUPFRvO0koXrQCDvdcd:-MVvbt_1-sPFdN5h5RAa:b-5jy0ao) ([raw file](https://github.com/josephsnyder/drake/blob/666928b2f99606f38f23480d606ffc83c3d5ad6e/tmp/autopybind11/AutoDiffXd_py.cpp#L30)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Names are now sorted; however, the ordering of overloads is still not sorted:
32bc265780

Can you ensure that the full signature is sorted, since there seems to be difference in how it's iterated upon in pygccxml / castxml / whatever?
</blockquote></details>

Ok.  With merge of https://gitlab.kitware.com/autopybind11/autopybind11/-/merge_requests/143, sorting now occurs on the same keys as Drake (name, file, file line no)


<!-- Sent from Reviewable.io -->

2021-03-16 15:51 UTC, merged

2021-03-18 14:49 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 500 files reviewed, 8 unresolved discussions

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MVvcGv3BypJ2frrlGi3:-MW4noosCtpfNKQEY7Kd:b-mcal79) (no related file):*
<details><summary><i>Previously, josephsnyder (Joseph Snyder) wrote…</i></summary><blockquote>

Per F2F with Jamie, we want to move forward with this to try and get the main pull request (https://github.com/RobotLocomotion/drake/pull/14265) merged before end of contract.
</blockquote></details>

@jamiesnape I think it's inefficient to have merged this for the sake of moving forward without concretely addressing my comments.

---


<!-- Sent from Reviewable.io -->

2021-03-18 14:53 UTC, EricCousineau-TRI reviewed
> *[Reviewable](https://reviewable.io/reviews/josephsnyder/drake/3)* status: 0 of 500 files reviewed, 8 unresolved discussions

*[a discussion](https://reviewable.io/reviews/josephsnyder/drake/3#-MVvcGv3BypJ2frrlGi3:-MW4oiYUDesL4LrNLsh-:b3dwo4n) (no related file):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

@jamiesnape I think it's inefficient to have merged this for the sake of moving forward without concretely addressing my comments.
</blockquote></details>

OK The generated bindings are still in the Drake PR.

Defects can be re-filed, but it's having to be replayed, and it makes Drake PR noisy. Oh well.

---


<!-- Sent from Reviewable.io -->